# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f74720701944d0838d8d657b393682aca783d5d783cbfcd567587a7e1b35fbe753b6471666e3fd196558d728f297f487a58e7c135a71beaf935de128b4d55cb9

test:
  secret_key_base: 8c93dfd71f69d13428bf5bb27a79b677fb53df35f5c95dec0aff0682927a21bf18a61084c35dc02f2aa6bce6bfbcfaea6413ef1e4c81c7abe70f9aea48e07641

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
